### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'deleteData' on 'CharacterData': The offset 2 is greater than the node's length (1).

### ISSUE THREAD

**Issue by ile** [derbyjs/saddle#18]
Bug: Derby throws error on an input that should work.

The code to reproduce with:

``` coffeescript
app.get '/', (page, model) ->
  q = model.at 'col.id'
  q.subscribe (err) ->  
    model.ref('_page.msg', q.at('msg'))
    page.render()
```

``` html
<Body:>
  <textarea rows="10">{{_page.msg}}</textarea>
```

How to reproduce:
- Focus into the textarea
- Press enter twice
- Press F5 and watch the JavaScript Console

The troublesome function: https://github.com/derbyjs/saddle/blob/master/index.js#L1082

**Comment by pypmannetjies** [comment]
Closing this issue due to staleness, please reach out if you are still experiencing this issue.
